schema: https://swapi-graphql.netlify.app/.netlify/functions/index

documents: "src/**/*.{graphql,js,ts,jsx,tsx}"

emitLegacyCommonJSImports: false
generates:
  ./src/gql/:
    preset: "client"
  ./src/gql/introspection.json:
    plugins:
      - urql-introspection
